Repository TUK-DP/frontend-v2, pull requests merged in 2024-07, with the labels that each got.

#15 [feat] 밑에서 올라오는 구조 BottomSheetLayout 구현
  src/App.jsx
  src/layouts/BottomSheetLayout.js
  src/pages/test/TestApp.jsx
  src/pages/test/TestBottomSheetTutorialPage.jsx
Labels: feat

#10 Publishing/7 회원가입, 로그인 퍼블리싱
  package-lock.json
  package.json
  src/App.jsx
  src/assets/AppLogo.png
  src/components/HeaderBar.jsx
  src/components/Spinner.jsx
  src/components/signup/ErrorMessage.jsx
  src/components/signup/InputStep1.jsx
  src/components/signup/InputStep2.jsx
  src/components/signup/PurpleButton.jsx
  src/components/signup/SignupStep.jsx
  src/components/signup/SwipeWrapper.jsx
  src/pages/Signin.jsx
  src/pages/Signup.jsx
  tailwind.config.js
Labels: publishing

#13 [publishing] 종이배경 컴포넌트
  src/assets/diary/backgroud_paper.png
  src/components/diary/PaperBackgroundWrapper.js
Labels: publishing

#17 [publishing] CalendarDetail 컴포넌트 퍼블리싱
  src/components/calendar_detail/CalendarDetail.js
  src/components/calendar_detail/DiaryDetailActionButton.js
  src/components/calendar_detail/icon/CheckDiaryIcon.js
  src/components/calendar_detail/icon/GoDrawingIcon.js
  src/components/calendar_detail/icon/GoRememoryIcon.js
  src/layouts/BottomSheetLayout.js
  src/pages/test/TestBottomSheetTutorialPage.jsx
  tailwind.config.js
Labels: publishing

#20 [refactor] 유효성 검사 로직들 재사용가능하게 리팩토링, useInput 커스텀 훅으로 signIn, signUp 상태 관리 로직 변경
  src/components/signup/InputStep1.jsx
  src/components/signup/InputStep2.jsx
  src/hooks/useInput.js
  src/pages/Signin.jsx
  src/pages/Signup.jsx
  src/utils/validator/input.js
Labels: refactor

#21 Publishing/14 그리기 도구 퍼블리싱
  package-lock.json
  package.json
  src/assets/drawingTools/colorPencil_apricot.png
  src/assets/drawingTools/colorPencil_babypink.png
  src/assets/drawingTools/colorPencil_black.png
  src/assets/drawingTools/colorPencil_blue.png
  src/assets/drawingTools/colorPencil_brown.png
  src/assets/drawingTools/colorPencil_coral.png
  src/assets/drawingTools/colorPencil_gray.png
  src/assets/drawingTools/colorPencil_green.png
  src/assets/drawingTools/colorPencil_navy.png
  src/assets/drawingTools/colorPencil_olive.png
  src/assets/drawingTools/colorPencil_orange.png
  src/assets/drawingTools/colorPencil_pink.png
  src/assets/drawingTools/colorPencil_plum.png
  src/assets/drawingTools/colorPencil_purple.png
  src/assets/drawingTools/colorPencil_rainbow.png
  src/assets/drawingTools/colorPencil_red.png
  src/assets/drawingTools/colorPencil_yellow.png
  src/assets/drawingTools/eraser.png
  src/components/draw/BrushSizeControl.js
  src/components/draw/CanvasPalette.js
  src/components/draw/ColorPickerComp.js
  src/components/draw/DrawingToolBar.js
  src/styles/inputCustum.css
  tailwind.config.js
Labels: publishing

#27 Publishing/24 다른사람이 그린 키워드 그림 리스트 퍼블리싱
  src/assets/remembrance/noKeyword.png
  src/assets/remembrance/questionMark.png
  src/components/draw/KeywordReferenceDrawingViewer.js
Labels: publishing

#32 [publishing] Calendar 컴포넌트 구현
  src/components/calendar/Calendar.jsx
  src/components/calendar/CalendarGrid.jsx
  src/components/calendar/CalendarMonthSelector.jsx
  src/utils/array/range.js
  src/utils/calendar/date.js
  tailwind.config.js
Labels: feat, chore, publishing

#26 [publishing] AI 채팅 안 ai 와 사용자 채팅 컴포넌트 퍼블리싱
  package-lock.json
  package.json
  src/components/helpWithAi/chat/Chat.jsx
  src/components/helpWithAi/chat/ImageBlock.jsx
  src/components/helpWithAi/chat/TextBlock.jsx
  src/components/helpWithAi/icon/AiProfileIcon.js
  tailwind.config.js
Labels: feat, chore, publishing

#29 Publishing/28 치매진단 시작 전 안내페이지 퍼블리싱
  src/App.jsx
  src/components/Button.js
  src/pages/dementiaDiagnosis/DiagnosisGuide.js
Labels: publishing

#41 [feat] header 레이아웃, 및 대부분의 페이지 이동 로직 구현
  src/App.jsx
  src/components/HeaderBar.jsx
  src/components/calendar/Calendar.jsx
  src/components/calendar/CalendarGrid.jsx
  src/components/calendar/CalendarMonthSelector.jsx
  src/components/calendar_detail/CalendarDetail.js
  src/components/diary/PaperBackgroundWrapper.js
  src/components/home/MainDementiaPreventionSection.js
  src/components/signup/SignupStep.jsx
  src/hooks/Diagnosis/useGoDiagnosisGuide.js
  src/hooks/diary/useGoDiary.js
  src/layouts/BottomSheetLayout.js
  src/layouts/HeaderBarLayout.js
  src/pages/Diary.jsx
  src/pages/DiaryDraw.jsx
  src/pages/Home.jsx
  src/pages/Signin.jsx
  src/pages/Signup.jsx
  src/pages/dementiaDiagnosis/DiagnosisGuide.js
  src/pages/test/TestBottomSheetTutorialPage.jsx
  src/utils/calendar/date.js
  tailwind.config.js
Labels: feat, chore

#43 [feat] NavBar 로직 구현
  src/App.jsx
  src/components/HeaderBar.jsx
  src/components/navbar/NavBar.jsx
  src/components/navbar/NavBarItem.jsx
  src/hooks/navbar/useNavBar.js
  src/hooks/useIsScrollDowning.js
  src/pages/MyPage.jsx
  src/stores/NavBarStore.js
Labels: feat

#38 [publishing]일기 회상 시작 전 페이지
  src/App.jsx
  src/assets/diary/noDiaryRecall.png
  src/assets/diary/questionPeople.png
  src/pages/DiaryRecall.jsx
  src/pages/NoDiaryRecall.jsx
  tailwind.config.js
Labels: publishing

#46 [feat] 아코디언 애니메이션 wrapper AccordionWrapper 구현
  src/components/signup/SignInOrUpInput.jsx
  src/components/wrapper/AccordionWrapper.jsx
Labels: feat

#49 [publishing] AI 도움받기 채팅창 로직 구현
  src/App.jsx
  src/components/HeaderBar.jsx
  src/components/helpWithAi/ChatAiImage.jsx
  src/components/helpWithAi/ChatAiText.jsx
  src/components/helpWithAi/ChatUserText.jsx
  src/components/helpWithAi/chat/Chat.jsx
  src/components/helpWithAi/chat/ImageBlock.jsx
  src/components/helpWithAi/chat/TextBlock.jsx
  src/components/helpWithAi/icon/ChatSendIcon.js
  src/hooks/HelpWithAi/useChatWithAi.js
  src/hooks/HelpWithAi/useGoHelpWithAiPage.js
  src/pages/DiaryDraw.jsx
  src/pages/HelpWithAi.jsx
  tailwind.config.js
Labels: feat, publishing

#51 Publishing/50 최근일기 조회 페이지 퍼블리싱
  src/App.jsx
  src/pages/mypage/RecentDiaries.js
Labels: publishing

#44 Publishing/30 치매진단 페이지 퍼블리싱
  src/App.jsx
  src/components/diagnosis/DiagnosisSlider.js
  src/components/diagnosis/Stepper.js
  src/hooks/Diagnosis/useDiagnosisSlider.js
  src/pages/dementiaDiagnosis/Diagnosis.js
Labels: publishing

#52 [publishing]AI 그림 투명도 조절 페이지
  src/App.jsx
  src/pages/draws/ControlPhotoOpacity.jsx
  tailwind.config.js
Labels: publishing

#54 Publishing/53 주변치매센터 검색 페이지 퍼블리싱
  src/App.jsx
  src/assets/dementiaCenter/search.png
  src/components/dementiaCenter/CenterList.js
  src/pages/dementiaCenter/DementiaCenter.js
Labels: publishing

#60 [publishing] 마이 페이지 퍼블리싱
  src/App.jsx
  src/components/mypage/ApiKeyInput.jsx
  src/components/mypage/FontSizeControl.jsx
  src/components/mypage/MyPageItem.jsx
  src/pages/MyPage.jsx
  src/pages/mypage/MyPage.jsx
  src/stores/NavBarStore.js
Labels: publishing

#57 [publishing] 일기 내용 확인 페이지 퍼블리싱
  src/App.jsx
  src/components/calendar_detail/CalendarDetail.js
  src/components/calendar_detail/DiaryDetailActionButton.js
  src/components/diary/PaperBackgroundWrapper.js
  src/components/signup/InputStep1.jsx
  src/components/signup/InputStep2.jsx
  src/hooks/HelpWithAi/useGoHelpWithAiPage.js
  src/hooks/diary/useGoDiary.js
  src/hooks/diary/useGoKeywordReference.js
  src/pages/auths/Signin.jsx
  src/pages/auths/Signup.jsx
  src/pages/diaryDetails/DiaryDetail.jsx
  src/pages/diarys/Diary.jsx
  src/pages/diarys/DiaryRecall.jsx
  src/pages/diarys/NoDiaryRecall.jsx
  src/pages/draws/DiaryDraw.jsx
  src/pages/draws/HelpWithAi.jsx
  src/pages/draws/KeywordReferenceImages.jsx
  src/stores/NavBarStore.js
  src/utils/api/dateConverter.js
Labels: feat, refactor, publishing

#65 [feat] user.controller 구현 및 jsDoc 작성
  src/apis/common.controller.js
  src/apis/user.controller.js
Labels: chore

#66 [publishing]체조 영상 페이지
  src/App.jsx
  src/assets/gym/GYM_DATA.js
  src/assets/gym/GymIcon.png
  src/components/home/SubDementiaPreventionSection.js
  src/hooks/gym/useGoGym.js
  src/pages/gym/Gym.jsx
  tailwind.config.js
Labels: publishing

#68 [refactor] 로그인,회원가입 로직 변경 및 퍼블리싱
  src/assets/AppLogo.png
  src/components/signup/InputStep1.jsx
  src/components/signup/InputStep2.jsx
  src/components/signup/SignupSlider.jsx
  src/components/signup/SignupStep.jsx
  src/hooks/inputs/useInput.js
  src/pages/auths/Signin.jsx
  src/pages/auths/Signup.jsx
  src/pages/draws/HelpWithAi.jsx
  src/utils/validator/input.js
Labels: refactor

#71 [feat] react query 설정 및 달력 check api 로직 구현
  package-lock.json
  package.json
  src/apis/common.controller.js
  src/apis/diary.controller.js
  src/components/calendar/CalendarGrid.jsx
  src/components/calendar/CalendarMonthSelector.jsx
  src/components/skeleton/ResponseSkeleton.js
  src/hooks/diary/queries/useFetchDiaryChecks.js
  src/index.js
  src/pages/diarys/Diary.jsx
  src/utils/api/dateConverter.js
  src/utils/api/delay.js
Labels: feat, chore

#63 [publishing] 치매진단 그래프 퍼블리싱
  package-lock.json
  package.json
  src/components/mypage/RecentDiagnosisGraph.jsx
Labels: feat, publishing

#91 [publishing] 치매 진단 결과 페이지 퍼블리싱
  src/App.jsx
  src/components/diagnosis/CompareBarChart.js
  src/components/diagnosis/DiagnosisSlider.js
  src/components/diagnosis/Stepper.js
  src/hooks/Diagnosis/useDiagnosisSlider.js
  src/pages/dementiaDiagnosis/Diagnosis.js
  src/pages/dementiaDiagnosis/DiagnosisGuide.js
  src/pages/dementiaDiagnosis/DiagnosisResult.js
  src/utils/diagnosis/getDiagnosisState.js
Labels: refactor, publishing

#90 [feat] 달력 상세 페이지 퍼블리싱, 달력 관련 api 연동, 달력 상태 전역 상태로 변경
  src/apis/diary.controller.js
  src/components/calendar/Calendar.jsx
  src/components/calendar/CalendarGrid.jsx
  src/components/calendar/CalendarMonthSelector.jsx
  src/components/calendar/NoDiary.jsx
  src/components/calendar_detail/CalendarDetail.js
  src/hooks/diary/queries/useFetchDiary.js
  src/hooks/diary/queries/useFetchDiaryChecks.js
  src/layouts/BottomSheetLayout.js
  src/pages/diarys/Diary.jsx
  src/stores/CalendarStore.js
  src/utils/api/dateConverter.js
Labels: feat, refactor, chore

#94 [refactor] App.jsx 라우터 구조 리팩토링
  src/App.jsx
  src/routes/AuthRoutes.js
  src/routes/DementiaDiagnosisRoutes.js
  src/routes/DiaryAndDrawRoutes.js
  src/routes/DiaryAndRecallRoutes.js
  src/routes/MainPageFeatureRoutes.js
  src/routes/MyPageFeatureRoutes.js
Labels: refactor

#92 [feat] 일기 디테일 페이지 일기 작성,수정 api 연동하기
  package-lock.json
  package.json
  src/apis/diary.controller.js
  src/components/Spinner.jsx
  src/components/calendar/NoDiary.jsx
  src/components/diaryDetail/DiaryKeywordImagesSlider.jsx
  src/hooks/diary/queries/useFetchDiary.js
  src/hooks/diary/queries/useFetchDiaryChecks.js
  src/hooks/diaryDetail/queries/useCreateDiary.js
  src/hooks/diaryDetail/queries/useUpdateDiary.js
  src/hooks/diaryDetail/useDiaryControl.js
  src/pages/diaryDetails/DiaryControlButton.jsx
  src/pages/diaryDetails/DiaryDetail.jsx
Labels: feat, chore

#97 Publishing/23 Color Picker 모달 퍼블리싱
  src/components/draw/ColorPickerComp.js
  src/constants/size.js
Labels: publishing

#96 Publishing/56 치매센터 map 페이지 퍼블리싱
  src/App.jsx
  src/pages/dementiaCenter/CenterMap.jsx
  src/routes/DementiaCenterRoutes.js
Labels: publishing

#95 Publishing/87 일기 회상 정답 확인 페이지 DiaryAndRecallRoutes 퍼블리싱
  src/assets/diaryRecall/collect_icon.png
  src/assets/diaryRecall/fault_icon.png
  src/components/wrapper/AccordionWrapper.jsx
  src/pages/diarys/DiaryRecallResult.jsx
  src/routes/DiaryAndRecallRoutes.js
Labels: publishing

#100 [feat] 글씨 크기 조절
  src/App.jsx
  src/components/mypage/FontSizeControl.jsx
  src/stores/FontSizeStore.js
Labels: feat

#101 [feat] kakaoMap 연동
  public/index.html
  src/components/dementiaCenter/KakaoMap.jsx
  src/pages/dementiaCenter/CenterMap.jsx
Labels: feat

#102 [Publishing/69]지는 가위바위보 게임 가이드 페이지, 게임 페이지 퍼블리싱, api 연동까지
  src/assets/game/paperIcon.png
  src/assets/game/rockIcon.png
  src/assets/game/scissorIcon.png
  src/components/game/GameIntroModal.jsx
  src/components/home/SubDementiaPreventionSection.js
  src/components/modals/ModalBackground.jsx
  src/pages/games/GameRockScissorPaper.jsx
  src/pages/games/RockScissorPaperIntro.jsx
  src/routes/MainPageFeatureRoutes.js
  tailwind.config.js
Labels: publishing

#103 Feat/74 주변치매센터 연동
  src/apis/center.controller.js
  src/components/dementiaCenter/CenterList.js
  src/components/dementiaCenter/KakaoMap.jsx
  src/hooks/DementiaCenter/useGetNearByCenter.js
  src/pages/dementiaCenter/CenterMap.jsx
  src/pages/dementiaCenter/DementiaCenter.js
  src/routes/DementiaCenterRoutes.js
Labels: feat

#104 Feat/72 로그인,회원가입, 자동로그인 로직 구현
  src/App.jsx
  src/apis/user.controller.js
  src/components/signup/InputStep1.jsx
  src/components/signup/InputStep2.jsx
  src/components/signup/SignInOrUpInput.jsx
  src/hooks/auth/query/useAutoLogin.js
  src/hooks/auth/query/useCheckAccountId.js
  src/hooks/auth/query/useSignIn.js
  src/hooks/auth/query/useSignUp.js
  src/pages/auths/Signin.jsx
  src/pages/auths/Signup.jsx
  src/stores/UserStore.js
  src/utils/auth/localStorageController.js
Labels: feat

#105 [Feat] Canvas 컴포넌트 그림 그리는 로직 구현
  src/components/draw/BackGroudCavnas.jsx
  src/components/draw/BrushSizeControl.js
  src/components/draw/CanvasPalette.js
  src/components/draw/CanvasSet.jsx
  src/components/draw/CanvasWrapper.jsx
  src/components/draw/ColorPickerComp.js
  src/components/draw/DrawingToolBar.js
  src/hooks/canvas/useDrawEvents.js
  src/pages/draws/DiaryDraw.jsx
  src/stores/DrawState.js
  src/stores/DrawingToolStore.js
  src/stores/Keyword.js
Labels: enhancement

#106 [publishing]게임 페이지 퍼블리싱 및 api 연동
  src/assets/game/colorMatchIcon.png
  src/assets/game/gameIcon.png
  src/components/game/GameIntroModal.jsx
  src/components/home/SubDementiaPreventionSection.js
  src/constants/gameInfo.js
  src/pages/games/ColorMatch.jsx
  src/pages/games/ColorMatchIntro.jsx
  src/pages/games/RockScissorPaper.jsx
  src/pages/games/RockScissorPaperIntro.jsx
  src/pages/games/SelectGames.jsx
  src/routes/MainPageFeatureRoutes.js
Labels: publishing

#108 [feat] 치매 진단 설문 API 연동
  src/apis/diagnosis.controller.js
  src/hooks/Diagnosis/queries/useGetDiagnosisQuiz.js
  src/hooks/Diagnosis/useDiagnosisSlider.js
  src/pages/dementiaDiagnosis/Diagnosis.js
  src/pages/dementiaDiagnosis/DiagnosisGuide.js
  src/pages/dementiaDiagnosis/DiagnosisResult.js
Labels: feat
