Repository TUK-DP/frontend-v2, pull requests merged in 2024-08, with the labels that each got.

#113 Refactor/110 useRequireAuth 구현, MyPage API 연동
  src/apis/diagnosis.controller.js
  src/apis/user.controller.js
  src/hooks/Diagnosis/queries/useFetchRecentDiagnosis.js
  src/hooks/auth/useRequireAuth.js
  src/hooks/diary/queries/useFetchDiary.js
  src/hooks/diary/queries/useFetchDiaryChecks.js
  src/hooks/user/query/useFetchUser.js
  src/pages/mypage/MyPage.jsx
  src/stores/UserStore.js
  src/utils/auth/localStorageController.js
Labels: feat

#111 Feat/86 일기 회상 문제 api 연동 + 문제 제출후 정답 확인 API 로직 까지 연동
  src/apis/diary.recall.controller.js
  src/components/calendar_detail/CalendarDetail.js
  src/hooks/diary/queries/useFetchRecallQuiz.js
  src/hooks/diary/useRecallTestSlider.js
  src/hooks/home/useGoHome.js
  src/pages/diarys/DiaryRecall.jsx
  src/pages/diarys/DiaryRecallResult.jsx
  src/pages/diarys/DiaryRecallTest.jsx
  src/pages/diarys/NoDiaryRecall.jsx
Labels: enhancement

#115 Feat/112 useFetchDiaryRecallQuiz 의 diaryId 수정, 그림 로직에서 사용되는 keyword 모두 useFetchDiary에서 가져오기
  src/components/diaryDetail/DiaryKeywordImagesSlider.jsx
  src/components/draw/CanvasSet.jsx
  src/components/draw/CanvasWrapper.jsx
  src/components/draw/KeywordSlider.jsx
  src/hooks/Diagnosis/queries/useFetchRecentDiagnosis.js
  src/hooks/Diagnosis/useDiagnosisSlider.js
  src/hooks/canvas/useFetchKeyword.js
  src/hooks/canvas/useGoDiaryDraw.js
  src/hooks/diaryDetail/queries/useCreateDiary.js
  src/hooks/diaryDetail/queries/useUpdateDiary.js
  src/pages/dementiaDiagnosis/DiagnosisResult.js
  src/pages/draws/DiaryDraw.jsx
  src/stores/Keyword.js
  src/stores/KeywordStore.js
Labels: enhancement

#117 Feat/78 최근 일기 목록 무한스크롤 Api 연동
  src/apis/diary.controller.js
  src/hooks/auth/query/useAutoLogin.js
  src/hooks/auth/useRequireAuth.js
  src/hooks/common/useScreenOn.js
  src/hooks/diary/queries/useFetchRecentDiary.js
  src/pages/mypage/MyPage.jsx
  src/pages/mypage/RecentDiaries.js
  src/utils/mock/diary/recent.js
Labels: feat

#120 [fix]isKeywordEmpty 변수 오류 해결
  src/components/draw/CanvasWrapper.jsx
  src/components/draw/KeywordSlider.jsx
  src/hooks/canvas/useFetchKeyword.js
  src/hooks/canvas/useFetchKeywords.js
Labels: bug

#121 Feat/81 AI에게 그림 도움받기 기능 구현
  src/apis/image.controller.js
  src/components/draw/KeywordSlider.jsx
  src/components/helpWithAi/chat/Chat.jsx
  src/components/mypage/ApiKeyInput.jsx
  src/hooks/HelpWithAi/query/useGenerateImage.js
  src/hooks/HelpWithAi/useChatWithAi.js
  src/pages/draws/HelpWithAi.jsx
  src/stores/ApiKeyStore.js
  src/stores/ChatLogStore.js
  src/stores/KeywordStore.js
Labels: feat

#125 Feat/116 그림일기 저장 로직 구현
  src/apis/image.controller.js
  src/components/diaryDetail/DiaryKeywordImagesSlider.jsx
  src/components/draw/CanvasSet.jsx
  src/components/draw/CanvasWrapper.jsx
  src/components/helpWithAi/chat/ImageBlock.jsx
  src/hooks/canvas/useDrawEvents.js
  src/hooks/canvas/useInitializeCanvas.js
  src/hooks/canvas/useResetAiIamges.js
  src/hooks/canvas/useSaveCanvas.js
  src/pages/diaryDetails/DiaryDetail.jsx
  src/stores/AiImagesStore.js
Labels: feat

#126 Feat/80 키워드 그림 api 연동
  src/apis/diary.controller.js
  src/components/draw/KeywordReferenceDrawingViewer.js
  src/components/draw/KeywordSlider.jsx
  src/hooks/diary/queries/useFetchKeywordPhotos.js
  src/pages/draws/DiaryDraw.jsx
Labels: feat

#128 Feat/118 로그인 화면 로고 클릭 시 홈화면 이동
  src/pages/auths/Signin.jsx
Labels: feat

#129 Refactor/123 다른 페이지 갔다와도 키워드 처음으로 안넘어가게 변경
  src/components/draw/CanvasWrapper.jsx
  src/components/draw/KeywordSlider.jsx
  src/hooks/canvas/useGoSelectedKeyword.js
  src/hooks/canvas/useResetAiIamges.js
  src/hooks/canvas/useResetCanvas.js
  src/pages/diaryDetails/DiaryDetail.jsx
  src/pages/draws/DiaryDraw.jsx
  src/stores/KeywordStore.js
Labels: enhancement

#130 Feat/127 AI 도움 받기 후, 투명도 조절
  src/components/draw/CanvasWrapper.jsx
  src/components/helpWithAi/chat/ImageBlock.jsx
  src/hooks/Diagnosis/useDiagnosisSlider.js
  src/hooks/canvas/useGoControlPhotoOpacity.js
  src/hooks/canvas/useGoDiaryDraw.js
  src/hooks/canvas/useInitializeCanvas.js
  src/pages/draws/ControlPhotoOpacity.jsx
  src/stores/AiImagesStore.js
  src/stores/DrawingToolStore.js
Labels: enhancement

#131 Feat/124 키워드 처음에서는 왼쪽 화살표, 마지막에서는 오른쪽 화살표 안보이게 구현
  src/components/draw/KeywordSlider.jsx
Labels: feat

#133 Chore/132 깃허브 액션 배포 스크립트 구현
  .github/workflows/deploy.yml
  .github/workflows/hofix.yml
  .github/workflows/testing.yml
  package.json
  public/index.html
Labels: feat, chore

#148 Publishing/142 일기 삭제버튼, 모달 추가 일기 새로고침 내용 초기화 문제 수정
  package-lock.json
  package.json
  src/apis/diary.controller.js
  src/hooks/diaryDetail/queries/useDeleteDiary.js
  src/hooks/diaryDetail/useDiaryControl.js
  src/pages/diaryDetails/DiaryControlButton.jsx
  src/pages/diaryDetails/DiaryDeleteModal.jsx
Labels: bug, publishing

#149 Publihsing/138 컬러매치 버튼 위치 수정
  src/components/home/SubDementiaPreventionSection.js
  src/pages/games/ColorMatchIntro.jsx
Labels: publishing

#151 Fix/146 사이트 이름 변경과 파비콘 기억함으로 변경
  public/favicon.ico
  public/index.html
Labels: chore

#150 Refactor/139 미래 일기 못하게 변경, 새로고침시 현재 날짜 안바뀌게 수정
  src/components/calendar/Calendar.jsx
  src/components/calendar/CalendarGrid.jsx
  src/components/calendar/CalendarMonthSelector.jsx
  src/hooks/diary/queries/useFetchDiaryChecks.js
  src/hooks/diaryDetail/queries/useCreateDiary.js
  src/hooks/diaryDetail/queries/useUpdateDiary.js
  src/pages/diarys/Diary.jsx
  src/pages/mypage/RecentDiaries.js
  src/stores/CalendarStore.js
  src/utils/calendar/date.js
Labels: feat, refactor

#152 [feat] 홈화면 치매센터 버튼 페이지 연결
  src/hooks/DementiaCenter/useGoDementiaCenter.js
  src/pages/Home.jsx
Labels: feat

#153 Publishing/140 키워드 간격, 치매진단 stepper 오류 수정
  src/components/diagnosis/Stepper.js
  src/components/diary/RecallTestSlider.js
Labels: publishing

#155 Refactor/143 그림일기 상태 저장 및 ai 크게보기 수정
  src/components/helpWithAi/chat/ImageBlock.jsx
  src/hooks/canvas/useDrawEvents.js
  src/hooks/canvas/useResetCanvas.js
  src/pages/draws/ControlPhotoOpacity.jsx
  src/stores/DrawState.js
Labels: refactor

#154 Publishing/145 그리기 도구 수정
  src/components/draw/CanvasPalette.js
  src/components/draw/ColorPickerComp.js
  src/styles/colorPicker.css
Labels: publishing

#157 Refactor/137 CalendarDetail, BottomSheete 리팩토링
  src/apis/diary.controller.js
  src/components/calendar_detail/CalendarDetail.js
  src/components/calendar_detail/icon/GoDrawingIcon.js
  src/hooks/diary/queries/useFetchDiaryChecks.js
  src/hooks/diaryDetail/queries/useDeleteDiary.js
  src/layouts/BottomSheetLayout.js
Labels: refactor

#156 Refactor/141 치매센터 Map 페이지 수정
  src/components/dementiaCenter/CenterList.js
  src/hooks/DementiaCenter/useGetNearByCenter.js
  src/pages/dementiaCenter/CenterMap.jsx
  src/pages/dementiaCenter/DementiaCenter.js
Labels: refactor

#158 Feat/144 그림 일기 저장 수정
  src/apis/image.controller.js
  src/components/diaryDetail/DiaryKeywordImagesSlider.jsx
  src/hooks/canvas/useSaveCanvas.js
  src/hooks/diary/queries/useFetchDiary.js
  src/styles/diarySliderDots.css
Labels: enhancement

#171 Publishing/166 HelpAIChat input 의 min-w 값 설정으로 튀어 나오지 않게 설정
  src/components/helpWithAi/chat/Chat.jsx
  src/pages/draws/HelpWithAi.jsx
Labels: publishing

#172 Fix/169 diary 삭제후 일기내용 이전거 사용하지 않도록 변경
  src/hooks/diaryDetail/useDiaryControl.js
Labels: bug

#173 Fix/172 그림 그린 이후 그림 있다는 내용으로 쿼리 캐시 초기화
  src/components/draw/CanvasWrapper.jsx
Labels: bug

#174 Refactor/162 일기 쓰러 가기 버튼 수정 및 마이페이지 폰트 크기 수정
  src/components/calendar/NoDiary.jsx
  src/components/mypage/FontSizeControl.jsx
  src/hooks/auth/useRequireAuth.js
  src/stores/FontSizeStore.js
Labels: refactor

#175 Publishing/163 치매센터 문구, input 타입 수정
  src/components/dementiaCenter/CenterList.js
  src/hooks/DementiaCenter/useGetNearByCenter.js
  src/pages/dementiaCenter/DementiaCenter.js
Labels: publishing

#176 [fix] 키워드 그림 참조 페이지 무한스크롤 수정
  src/hooks/diary/queries/useFetchKeywordPhotos.js
Labels: bug

#177 [publishing] 최근일기 버튼 > 추가
  src/pages/mypage/MyPage.jsx
Labels: publishing

#178 [feat]AI 도움 받기 후 캔버스 이동 오류 해결
  src/components/draw/CanvasWrapper.jsx
  src/components/draw/KeywordSlider.jsx
Labels: enhancement

#182 Fix/170 뒤로가기 오류 해결과 flutter에서 넘긴 위치정보 오류 해결
  src/App.jsx
  src/components/dementiaCenter/CenterList.js
  src/hooks/DementiaCenter/useGetAddress.js
  src/hooks/DementiaCenter/useGetNearByCenter.js
  src/hooks/DementiaCenter/useGetPosition.js
  src/hooks/DementiaCenter/useSetFlutterPostion.js
  src/hooks/common/useDebounce.js
  src/pages/dementiaCenter/DementiaCenter.js
  src/pages/draws/ControlPhotoOpacity.jsx
  src/routes/MainPageFeatureRoutes.js
  src/stores/PositionStore.js
Labels: bug, feat
